repos:
-   repo: local
    hooks:
    -   id: mementor-snapshot
        name: Generate Documentation Snapshot
        entry: python3 scripts/hooks/pre_commit.py
        language: python
        pass_filenames: false
        types: [text]
        stages: [commit]
        additional_dependencies: ['pystache>=0.6.0']
